/**
	Generated using Godot Bindings Generator for Haxe.
	https://github.com/SomeRanDev/Haxe-GodotBindingsGenerator
**/
package godot;
/**
	Custom code to generate previews. Please check [code]file_dialog/thumbnail_size[/code] in [EditorSettings] to find out the right size to do previews at.
**/
@:generated_godot_api @:bindings_api_type("class") @:is_refcounted(true) @:is_instantiable(true) @:api_type("editor") @:is_resource(true) @:is_node(false) extern class EditorResourcePreviewGenerator extends godot.RefCounted {
	/**
		Returns [code]true[/code] if your generator supports the resource of type [param type].
	**/
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(null)
	@:hash_compatibility(null)
	public function _handles(type:String):Bool;
	/**
		Generate a preview from a given resource with the specified size. This must always be implemented.
		Returning an empty texture is an OK way to fail and let another generator take care.
		Care must be taken because this function is always called from a thread (not the main thread).
		[param metadata] dictionary can be modified to store file-specific metadata that can be used in [method EditorResourceTooltipPlugin._make_tooltip_for_path] (like image size, sample length etc.).
	**/
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(null)
	@:hash_compatibility(null)
	public function _generate(resource:godot.Resource, size:godot.Vector2i, metadata:godot.Dictionary):godot.Texture2D;
	/**
		Generate a preview directly from a path with the specified size. Implementing this is optional, as default code will load and call [method _generate].
		Returning an empty texture is an OK way to fail and let another generator take care.
		Care must be taken because this function is always called from a thread (not the main thread).
		[param metadata] dictionary can be modified to store file-specific metadata that can be used in [method EditorResourceTooltipPlugin._make_tooltip_for_path] (like image size, sample length etc.).
	**/
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(null)
	@:hash_compatibility(null)
	public function _generate_from_path(path:String, size:godot.Vector2i, metadata:godot.Dictionary):godot.Texture2D;
	/**
		If this function returns [code]true[/code], the generator will automatically generate the small previews from the normal preview texture generated by the methods [method _generate] or [method _generate_from_path].
		By default, it returns [code]false[/code].
	**/
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(null)
	@:hash_compatibility(null)
	public function _generate_small_preview_automatically():Bool;
	/**
		If this function returns [code]true[/code], the generator will call [method _generate] or [method _generate_from_path] for small previews as well.
		By default, it returns [code]false[/code].
	**/
	@:return_value_meta(null)
	@:is_const(true)
	@:is_static(false)
	@:is_vararg(false)
	@:is_virtual(true)
	@:hash(null)
	@:hash_compatibility(null)
	public function _can_generate_small_preview():Bool;
}